# Generated by Django 5.2.1 on 2025-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Очікується'), ('CONFIRMED', 'Підтверджено'), ('CANCELLED', 'Відміненно'), ('DECLINED', 'Відмовлено')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rent',
                'ordering': ['-created_at'],
            },
        ),
    ]
