# Generated by Django 5.2.1 on 2025-05-31 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_rent_status'),
        ('rooms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rent',
            name='booking_valid_date_range',
        ),
        migrations.RemoveConstraint(
            model_name='rent',
            name='unique_booking_per_user_rent_period',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='lessee',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='rent',
        ),
        migrations.AddField(
            model_name='rent',
            name='guest',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'GUEST'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rent',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='rooms.room'),
        ),
        migrations.AddConstraint(
            model_name='rent',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='rent_valid_date_range'),
        ),
        migrations.AddConstraint(
            model_name='rent',
            constraint=models.UniqueConstraint(fields=('guest', 'room', 'start_date', 'end_date'), name='unique_booking_per_user_rent_period'),
        ),
    ]
