# Generated by Django 5.2.1 on 2025-05-26 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=65)),
                ('street', models.CharField(max_length=128)),
                ('house_number', models.CharField(blank=True, max_length=16, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=16, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rooms_count', models.PositiveSmallIntegerField(default=0)),
                ('room_type', models.CharField(choices=[('one_room_apartment', '1-кімнатна квартира (вітальня і спальня разом, з кухнею та ванною)'), ('two_room_apartment', '2-кімнатна квартира (спальня та вітальня окремо)'), ('three_room_apartment', '3-кімнатна квартира (спальня, дитяча або кабінет, вітальня)'), ('shared_apartment', 'Кімната у спільній квартирі (спільне житло з іншими)'), ('granny_flat', 'Окрема невелика квартира в межах приватного будинку'), ('apartment', 'Квартира в багатоквартирному будинку'), ('single_family_house', 'Будинок на одну родину'), ('two_family_house', 'Будинок на дві родини'), ('townhouse', 'Таунхаус (ряд будинків з’єднані стіною)'), ('semi_detached_house', 'Половина дуплексу (спарений будинок)'), ('luxury_apartment', 'Сучасна або елітна квартира з повним обладнанням')], max_length=36)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to='rooms.address')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rent',
            },
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('country', 'city', 'street', 'apartment_number'), name='unique_address_with_apartment'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('title', 'address', 'is_deleted'), name='unique_listing_title_desc_address_not_deleted'),
        ),
    ]
